homework
BiazlepkinAS/Group09-2020_ITAcademy pull request #1
Opened 2020-09-23 09:27 UTC by BiazlepkinAS

2020-09-23 13:23 UTC, ApproachDev requested changes
пока поставлю 7, но жду вопросов или доработки

2020-09-23 13:23 UTC, ApproachDev commented on LS5 Homework.playground/Contents.swift
> +var multiCarWash = TimeOfCarwash.multiplu
Похоже rawvalue немного не так понимаешь - rawValue это не значение, которое мы можем поместить в инам, это просто код отдельно взятого кейса

2020-09-23 13:23 UTC, ApproachDev commented on LS5 Homework.playground/Contents.swift
> +}
не понятен юзкейс

2020-09-23 13:23 UTC, ApproachDev commented on LS5 Homework.playground/Contents.swift
> +}
технически возможно, но для опционалов свитч слишком массивная конструкция

2020-09-28 07:17 UTC, vadzimzhuk reviewed
Пока поставлю 8, если пофиксишь первое задание, то 9

2020-09-28 07:17 UTC, vadzimzhuk commented on LS6 Homework.playground/Contents.swift
> +func summOfWord (word: String?, line: Array<String>?)  -> Int{
Нужно было не массива стринг передавать, а стринг и в стринге уже искать слово.
На занятии покажу

2020-09-28 07:17 UTC, vadzimzhuk commented on LS6 Homework.playground/Contents.swift
> +//MARK:- 2. Написать алгоритм с помощью цикла DO-WHILE который добавляет в массив [Int] элементы (можно одинаковые, можно рандомные) до тех пор, пока сумма элементов массива меньше 100
хорошо

2020-09-28 07:17 UTC, vadzimzhuk commented on LS6 Homework.playground/Contents.swift
> +//MARK:- 3. Написать 1 алгоритм сортировки элементов массива [Int]
хорошо

2020-09-28 15:20 UTC, merged